### PR TITLE
RONDB-462: Fix Changing Mounted Desired State File from Host

### PR DESCRIPTION
**Pull request by olapiv**
https://hopsworks.atlassian.net/browse/RONDB-462

### CODE REVIEW

**Comment by svenssonaxel** [comment]
This offloads the problem to the user. Wouldn't it be better to solve it ourselves?

Are you trying to avoid having a directory just for one file? I agree that it's a little ugly, but IMO letting actual usability suffer is worse. Are there more downsides with the directory workaround?

**Comment by olapiv** [comment]
Nope, that's the only downside 🙃

**Comment by olapiv** [comment]
Could also consider mounting the root directory actually. But then might have to use a different directory inside the container.

**Comment by svenssonaxel** [comment]
Is the desired state file the only file necessary in the current target directory inside the container (`/home/flask_server`)? If so, then that seems like a relatively clean solution since we don't need to change the image.

**Comment by olapiv** [comment]
Nope, all the Python files are in there 🤪

**Comment by svenssonaxel** [comment]
Ok, so if we want to mount a directory, the flask image will probably have to change anyways? Is that a big problem?

**Comment by olapiv** [comment]
Not really, it might just take 10-15min to test and then 1h CI to wait for the images to build.

**Review by svenssonaxel — APPROVED** [review]
Haha, so you managed to avoid the extra directory on the host anyways!

**Comment by olapiv** [comment]
Yep.. 😌

**Pull request merged**
